name: Maven Dependency Tree Submission

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean install

    - name: Generate Dependency Tree
      run: mvn dependency:tree -DoutputFile=dependency-tree.txt

    - name: Submit Dependency Tree to GitHub
      uses: actions/upload-artifact@v3
      with:
        name: dependency-tree
        path: dependency-tree.txt
